export const pick = (value, lang) => value && typeof value === "object" && !Array.isArray(value) && ("ko" in value || "en" in value) ? value[lang] ?? value.ko : value;

export const portfolio = {
  name: { ko: "조지관", en: "Jigwan Joe" },
  role: { ko: "IT 시스템 및 소프트웨어 품질 엔지니어", en: "IT Systems & Software Quality Engineer" },
  ui: {
    about: { ko: "소개", en: "About" }, projects: { ko: "프로젝트", en: "Projects" }, credentials: { ko: "이력", en: "Credentials" }, contact: { ko: "연락", en: "Contact" },
    viewWork: { ko: "대표 프로젝트 보기", en: "View selected work" }, resume: { ko: "PDF로 저장", en: "Save as PDF" }, skipToContent: { ko: "본문으로 바로가기", en: "Skip to content" }, languageLabel: { ko: "영문으로 보기", en: "View in Korean" },
    themeToLight: { ko: "라이트 모드로 보기", en: "Use light mode" }, themeToDark: { ko: "다크 모드로 보기", en: "Use dark mode" },
    menuOpen: { ko: "메뉴 열기", en: "Open menu" }, menuClose: { ko: "메뉴 닫기", en: "Close menu" },
    mobileNavigation: { ko: "모바일 포트폴리오 메뉴", en: "Mobile portfolio navigation" },
    closeDialog: { ko: "닫기", en: "Close dialog" },
    projectDeepDive: { ko: "프로젝트 상세 보기", en: "View project details" },
    evidenceLinks: { ko: "검증 근거", en: "Evidence" },
    viewEvidence: { ko: "검증 근거 보기", en: "View evidence" },
    evidenceModalIntro: { ko: "대표 결과와 공개된 검증 자료를 한 곳에서 확인할 수 있습니다.", en: "Review the key outcomes and public validation sources in one place." },
  },
  hero: {
    eyebrow: ["BACKEND", "SYSTEMS", "SOFTWARE QUALITY"],
    title: { ko: "만들고 검증해 배포합니다", en: "Build and verify before shipping" },
    summary: { ko: "백엔드와 데이터 시스템을 만들고 테스트와 운영 지표로 확인합니다.", en: "I build backend and data systems, then verify them with tests and operational signals." },
    photoAlt: { ko: "조지관 프로필 사진", en: "Portrait of Jigwan Joe" },
    quickFacts: [
      { value: "4.04 / 4.5", label: { ko: "학점", en: "GPA" } },
      { value: { ko: "경기대 컴퓨터공학부", en: "Computer Engineering" }, label: { ko: "2026.02 졸업", en: "Graduated 2026.02" } },
      { kind: "list", label: { ko: "자격증", en: "Certificates" }, items: ["정보처리기사", "SQLD", "ADsP", "CSTS"] },
      { kind: "list", label: { ko: "어학", en: "Language" }, items: ["OPIc IH", "TOEIC 765"] },
    ],
  },
  proof: { title: { ko: "핵심 성과", en: "Key outcomes" }, items: [
    { kicker: { ko: "운영", en: "DELIVERY" }, value: { ko: "Canary 10% → 100%", en: "Canary 10% → 100%" }, label: { ko: "검증 후 API 전면 배포", en: "Promoted the API to full production after staged validation" } },
    { kicker: { ko: "품질", en: "QUALITY" }, value: { ko: "OCR 배포 보류 → 재출시", en: "OCR held → re-shipped" }, label: { ko: "잔여 오답을 근거로 보류하고 확인 흐름 개선 후 재출시", en: "Held the release over residual OCR errors, then re-shipped after improving the confirmation flow" } },
    { kicker: { ko: "성과", en: "RECOGNITION" }, value: { ko: "논문 2편과 수상 2회", en: "2 papers and 2 awards" }, label: { ko: "학회 논문 공저와 두 차례 수상", en: "Conference co-authorship and two awards" } },
  ] },
  about: {
    eyebrow: { ko: "HOW I WORK", en: "HOW I WORK" }, title: { ko: "구현부터 운영까지 이어서 봅니다", en: "I connect implementation through operations" },
    copy: { ko: "데이터 흐름부터 배포 환경과 사용자 경험까지 함께 확인합니다.", en: "I check the full path from data flow to deployment and user experience." },
    strengths: [
      { title: { ko: "측정하고 판단합니다", en: "Measure, then decide" }, copy: { ko: "운영 조건과 같은 환경에서 RAG 검색을 비교해 필수 지표가 떨어진 리랭커는 배포하지 않았습니다.", en: "I compared RAG retrieval under production-like conditions and kept a reranker out when required metrics regressed." } },
      { title: { ko: "경계를 명확히 설계합니다", en: "Design clear boundaries" }, copy: { ko: "Spring Boot API와 Python ML 서비스를 분리하고 팀 프로젝트에서도 담당 범위와 인터페이스를 명확히 했습니다.", en: "I separated Spring Boot APIs from Python ML services and kept team ownership boundaries explicit." } },
      { title: { ko: "운영까지 확인합니다", en: "Verify operations" }, copy: { ko: "CI/CD와 테스트를 운영 흐름에 포함하고 백그라운드 동작과 개인정보 처리까지 직접 검증했습니다.", en: "I include CI/CD and tests in the delivery flow, then verify background behavior and privacy constraints." } },
    ],
  },
  projects: {
    eyebrow: { ko: "SELECTED WORK", en: "SELECTED WORK" }, title: { ko: "판단과 결과가 보이는 프로젝트", en: "Projects built around decisions and results" },
    copy: { ko: "맡은 문제와 판단 과정에 집중하고 결과에는 검증 근거를 연결했습니다.", en: "Each project focuses on the problem I owned, the decision I made, and the evidence behind the result." },
    featured: [
      {
        title: "혜택나침반", titleLines: [{ ko: "혜택나침반", en: "BenefitCompass" }], type: [{ ko: "개인", en: "Personal" }, { ko: "대표 프로젝트", en: "Flagship project" }], period: "2026.06 — 2026.09",
        lead: { ko: "공식 정책을 한 검색 경로로 통합한 RAG 서비스입니다. 검색된 정책만 근거로 답하도록 설계했습니다.", en: "A RAG service that unifies official policies into one search path and answers only from retrieved policy evidence." },
        tech: ["Spring Boot", "FastAPI", "pgvector", "React", "E5", "Prometheus"],
        visibleDetailIndexes: [1, 2],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "수천 개 정책이 흩어져 있고, 키워드 검색만으로는 자신에게 맞는 제도를 찾기 어려웠습니다.", en: "Thousands of policies were fragmented, and keyword search made relevant programs hard to discover." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "두 공식 출처의 13,589개 정책을 하나의 검색 경로로 통합했습니다. 17,609개 청크에서 임베딩 누락 0건을 확인했습니다.", en: "I unified 13,589 policies from two official sources into one search path and verified zero missing embeddings across 17,609 chunks." } },
          { label: { ko: "판단", en: "Decision" }, copy: { ko: "지역 데이터는 신뢰도가 부족해 제외했습니다. 리랭커는 필수 지표가 나빠져 배포하지 않았습니다.", en: "I excluded unreliable regional data and kept the reranker out when required metrics regressed." } },
          { label: { ko: "배포와 운영", en: "Delivery & operations" }, copy: { ko: "무트래픽 검증 뒤 API를 10% canary에서 100%로 승격하고 rollback 경로를 보존했습니다. 요청 ID와 메트릭으로 API / ML / DB 구간을 나눠 관측했습니다.", en: "I promoted the API from a 10% canary to 100% after no-traffic validation, preserved rollback, and separated API, ML, and DB observability." } },
          { label: { ko: "한계", en: "Limit" }, copy: { ko: "첫 요청 지연은 scale-to-zero 비용 절충으로 남아 있습니다. 더 강한 사용자 의도 평가도 설계했지만 유효한 canonical 평가까지 완료되지 않아 성능 개선으로 주장하지 않았습니다.", en: "Cold first-request latency remains a scale-to-zero cost trade-off. I also designed a stronger user-intent evaluation, but it did not reach a valid canonical result, so I did not turn it into a performance claim." } },
        ],
        results: [{ value: "13,589", label: { ko: "공식 정책", en: "official policies" } }, { value: "17,609", label: { ko: "검색 청크", en: "search chunks" } }, { value: "0", label: { ko: "임베딩 누락", en: "missing embeddings" } }],
        architecture: {
          title: { ko: "검색과 응답 경계", en: "Search & response boundaries" },
          sources: [{ ko: "온통청년", en: "Youth policies" }, { ko: "정부24", en: "Gov24" }],
          stages: [
            { name: "React", copy: { ko: "검색 UI", en: "Search UI" } },
            { name: "Spring Boot", copy: { ko: "정책 API", en: "Policy API" } },
            { name: "FastAPI", copy: { ko: "임베딩 / 검색", en: "Embedding & retrieval" } },
            { name: "PostgreSQL / pgvector", copy: { ko: "정책 / 벡터 저장", en: "Policy & vector store" } },
          ],
          note: { ko: "Prometheus와 request ID로 API / ML / DB 구간을 분리해 관측", en: "Prometheus and request IDs separate API, ML, and DB observability." },
        },
        links: [{ href: "https://jgjoe.github.io/benefit-compass", label: { ko: "데모 보기", en: "View demo" } }, { href: "https://github.com/jgjoe/benefit-compass", label: { ko: "코드 보기", en: "View code" } }, { href: "https://github.com/jgjoe/benefit-compass/tree/main/eval", label: { ko: "평가셋과 측정 스크립트", en: "Evaluation set & scripts" } }, { href: "https://github.com/jgjoe/benefit-compass/blob/main/docs/operations/PRODUCTION_LAB_2_2026-07-21.md", label: { ko: "운영 실험 기록", en: "Production lab record" } }, { href: "https://github.com/jgjoe/benefit-compass/blob/main/docs/operations/RUNBOOK.md", label: { ko: "운영 런북", en: "Runbook" } }],
        media: { type: "image", src: "/benefit-compass-demo.png", host: "jgjoe.github.io/benefit-compass", alt: { ko: "혜택나침반의 월세 지원 검색 결과", en: "BenefitCompass search results for rental support" }, caption: { ko: "실제 배포 환경에서 확인한 검색 결과", en: "Search result captured from the live deployment" } },
      },
      {
        title: "오늘도 신선", titleLines: [{ ko: "오늘도 신선", en: "Fridge D-Day" }], type: [{ ko: "개인", en: "Solo" }, { ko: "Android 공개 출시", en: "Android release" }, "Closed Alpha"], period: { ko: "2025.09 — 진행 중", en: "2025.09 — Present" },
        lead: { ko: "OCR로 유통기한 입력을 줄이고 이미지는 기기 안에서 처리하는 Android 앱입니다. ONEstore v2.0.0과 Google Play Closed Alpha까지 출시했습니다.", en: "An Android expiry-date app with on-device OCR, publicly shipped as ONEstore v2.0.0 and Google Play Closed Alpha." },
        tech: ["Kotlin", "Jetpack Compose", "Room", "WorkManager", "ML Kit OCR", "MVVM"],
        visibleDetailIndexes: [1, 2],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "기존 앱은 수동 입력이 번거롭고 인터넷 연결과 개인정보 수집에 대한 부담이 있었습니다.", en: "Existing apps relied on tedious manual input and raised concerns around connectivity and personal data." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "OCR 기반 입력과 로컬 저장을 구현했습니다. 알림부터 위젯과 백업/복원까지 단독으로 완성했습니다.", en: "I built OCR input and local storage, then completed notifications, widgets, and backup/restore solo." } },
          { label: { ko: "판단", en: "Decision" }, copy: { ko: "이미지는 기기 안에서만 처리했습니다. 잔여 OCR 오답이 있는 후보는 자동 게이트를 통과해도 배포하지 않았습니다.", en: "Images stay on-device, and I did not ship candidates with residual OCR errors even after automated gates passed." } },
          { label: { ko: "품질 검증", en: "Quality gate" }, copy: { ko: "독립 한국 라벨 55장을 고정 회귀셋으로 반복 검증하고, 잔여 오인식과 표본 공백이 남은 후보는 자동 게이트를 통과해도 배포를 보류했습니다. 최종 v2.0.0/code5 exact RC는 JVM unit 107/107, lint 0 errors, Galaxy A32 non-OCR instrumentation 65/65를 통과했습니다.", en: "I repeatedly tested OCR changes against a fixed set of 55 independent Korean labels and held a candidate despite passing automated gates when residual misreads and coverage gaps remained. The final v2.0.0/code5 exact RC passed 107/107 JVM unit tests, lint with zero errors, and 65/65 non-OCR instrumentation tests on a Galaxy A32." } },
          { label: { ko: "그 다음", en: "What followed" }, copy: { ko: "인식 날짜를 사용자가 확인해야 저장되도록 바꿔 v1.0.2로 재출시한 뒤, bundled Korean OCR과 실기기 회귀를 검증했습니다. 이어 4명 usability에서 반복 마찰을 찾아 수정하고 affected user 재검증을 거쳐 v2.0.0/code5를 ONEstore에 공개 배포하고 Google Play closed Alpha에도 출시했습니다. Play의 14일 요건과 Production 공개는 아직 진행 중입니다.", en: "I required users to confirm recognized dates before saving and re-released v1.0.2, then verified bundled Korean OCR and same-device regression. After a four-person usability round exposed repeated friction, I fixed those flows, retested them with affected users, publicly shipped v2.0.0/code5 on ONEstore, and released it to Google Play closed Alpha. Play's 14-day requirement and Production release are still in progress." } },
        ],
        results: [{ value: { ko: "검증 통과", en: "All checks passed" }, label: { ko: "JVM 107/107\nA32 65/65", en: "JVM 107/107\nA32 65/65" } }, { value: { ko: "Closed Alpha", en: "Closed Alpha" }, label: { ko: "Google Play v2.0.0/code5", en: "Google Play v2.0.0/code5" } }, { value: { ko: "공개 3버전", en: "3 public versions" }, label: { ko: "ONEstore v1.0 → v1.0.2 → v2.0.0", en: "ONEstore v1.0 → v1.0.2 → v2.0.0" } }],
        links: [{ href: "https://m.onestore.co.kr/v2/ko-kr/app/0001003331", label: { ko: "스토어에서 보기", en: "View in store" } }, { href: "https://github.com/jgjoe/Fridge-D-Day", label: { ko: "코드 보기", en: "View code" } }, { href: "https://github.com/jgjoe/Fridge-D-Day/blob/main/QA_RELEASE_RECORD.md", label: { ko: "QA와 릴리스 기록", en: "QA & release record" } }, { href: "https://github.com/jgjoe/Fridge-D-Day/blob/main/docs/qa/OCR_BENCHMARK.md", label: { ko: "OCR 벤치마크", en: "OCR benchmark" } }, { href: "https://github.com/jgjoe/Fridge-D-Day/blob/main/.github/workflows/android-ci.yml", label: { ko: "CI 설정", en: "CI workflow" } }],
        media: { type: "gallery", label: { ko: "오늘도 신선 v2 대표 화면", en: "Fridge D-Day v2 highlights" }, images: [
          { src: "/today-fresh-1.png", alt: { ko: "오늘도 신선 v2 Today 화면", en: "Fridge D-Day v2 Today screen" } },
          { src: "/today-fresh-2.png", alt: { ko: "오늘도 신선 v2 Scan 화면", en: "Fridge D-Day v2 Scan screen" } },
          { src: "/today-fresh-3.png", alt: { ko: "오늘도 신선 v2 Record 화면", en: "Fridge D-Day v2 Record screen" } },
        ] },
      },
      {
        title: "길동이 AI 차량 어시스턴트", titleLines: [{ ko: "길동이", en: "GildongE" }, { ko: "AI 차량 어시스턴트", en: "AI Vehicle Assistant" }], type: [{ ko: "6인 팀", en: "Team of 6" }, { ko: "백엔드 / DB 담당", en: "Backend / DB owner" }], period: "2025.03 — 2025.06",
        lead: { ko: "여러 장치의 차량 데이터를 처리하는 Spring Boot 백엔드를 맡았습니다.", en: "I owned the Spring Boot backend that processed vehicle data from multiple devices." },
        tech: ["Java 17", "Spring Boot", "MongoDB", "Spring Data MongoDB", "Kakao OAuth API", "OpenAPI"],
        visibleDetailIndexes: [0, 1],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "장치별 형식이 다른 차량 데이터를 사용자 단위로 다룰 서버가 필요했습니다.", en: "The team needed a backend that could normalize device-specific vehicle data per user." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "차량 도메인 REST API와 MongoDB 모델을 설계했습니다. 카카오 사용자 흐름과 주간 평균 집계도 구현했습니다.", en: "I designed the vehicle-domain REST APIs and MongoDB models, plus Kakao user flows and weekly aggregates." } },
          { label: { ko: "담당 범위", en: "My scope" }, copy: { ko: "6인 팀에서 차량 도메인 백엔드와 MongoDB 데이터 모델을 담당했습니다.", en: "In a six-person team, I owned the vehicle-domain backend and MongoDB data model." } },
        ],
        results: [{ value: { ko: "은상", en: "Silver" }, label: { ko: "캡스톤디자인 경진대회", en: "Capstone Design award" } }, { value: { ko: "1편", en: "1" }, label: { ko: "학회 논문", en: "Conference paper" } }, { value: { ko: "5개", en: "5" }, label: { ko: "백엔드 도메인", en: "backend domains" } }],
        links: [{ href: "https://github.com/jgjoe/gildongE", label: { ko: "백엔드 코드 보기", en: "View backend code" } }],
        media: { type: "poster", src: "/gildongE_poster.jpg", alt: { ko: "길동이 프로젝트 포스터", en: "GildongE project poster" } },
      },
    ],
    posterOpen: { ko: "프로젝트 포스터 보기", en: "View project poster" },
    posterClose: { ko: "프로젝트 포스터 닫기", en: "Hide project poster" },
    moreEyebrow: { ko: "MORE WORK", en: "MORE WORK" }, moreTitle: { ko: "다른 환경에서도 문제를 풀어봤습니다", en: "More problems, different environments" },
    more: [
      { title: { ko: "쓰담", en: "SSeudam" }, type: ["YOLOv8", "Android", "Robot"], link: null, copy: { ko: "실시간 객체 탐지와 로봇 연동을 맡아 2024 한국정보기술학회 대학생 논문경진대회 우수논문상을 받았습니다.", en: "I handled real-time object detection and robot integration in a project that received a 2024 KIIT student paper award." }, media: { src: "/ssodam_poster.jpg", alt: { ko: "쓰담 프로젝트 포스터", en: "SSeudam project poster" } } },
      { title: "movie_diary", type: ["React", "FastAPI", "Cloud Run"], link: "https://github.com/jgjoe/movie_diary", copy: { ko: "감정 기반 영화 추천 서비스로 외부 API 연동과 Cloud Run 배포 자동화를 구현했습니다.", en: "I built an emotion-based film recommendation service with third-party APIs and Cloud Run deployment automation." } },
      { title: "Build-Your-Health", type: ["JSP/Servlet", "MySQL"], link: "https://github.com/jgjoe/Build-Your-Health", copy: { ko: "건강 기록부터 쇼핑과 게시판, 관리자 기능까지 단독 구현한 MVC 웹 애플리케이션입니다.", en: "Solo MVC web app spanning health logs, commerce, community, and admin CRUD." } },
      { title: "dynamic_scraper", type: ["Flask", "BeautifulSoup"], link: "https://github.com/jgjoe/dynamic_scraper", copy: { ko: "사이트별 파서와 캐시를 적용해 채용 정보를 수집하고 CSV로 내보내는 크롤러입니다.", en: "A job-posting crawler with per-site parsers, response caching, and CSV export." } },
    ],
  },
  credentials: {
    eyebrow: { ko: "CREDENTIALS", en: "CREDENTIALS" }, title: { ko: "기본기를 증명하는 이력", en: "Credentials that support the work" }, skillsTitle: { ko: "핵심 기술", en: "CORE STACK" },
    groups: [
      { title: { ko: "학력", en: "Education" }, items: [{ ko: "경기대학교 컴퓨터공학부 졸업", en: "B.S. in Computer Engineering, Kyonggi University" }, { ko: "2020.03 — 2026.02 / 학점 4.04/4.5", en: "Mar. 2020 — Feb. 2026 / GPA 4.04/4.5" }] },
      { title: { ko: "자격증", en: "Certificates" }, items: ["정보처리기사", "SQLD", "ADsP", "CSTS Foundation Level"] },
      { title: { ko: "연구와 수상", en: "Research & awards" }, items: [{ ko: "한국정보기술학회 논문 2편 공저", en: "Co-author of 2 KIIT conference papers" }, { ko: "2025 산학협력 캡스톤디자인 경진대회 심화캡스톤디자인 부문 은상", en: "2025 Industry-Academia Capstone Design Competition, Advanced Division Silver Prize" }, { ko: "2024 한국정보기술학회 대학생 논문경진대회 우수논문상", en: "2024 KIIT Student Paper Competition, Outstanding Paper Award" }] },
    ],
  },
  skills: [
    { title: { ko: "언어와 백엔드", en: "Languages & Backend" }, items: ["Java", "Kotlin", "Python", "Spring Boot", "FastAPI", "REST API", "JSP/Servlet"] },
    { title: { ko: "데이터와 AI", en: "Data & AI" }, items: ["PostgreSQL / pgvector", "MongoDB", "MySQL", "RAG", { ko: "임베딩 / 리랭킹", en: "Embedding & reranking" }] },
    { title: { ko: "품질과 배포", en: "Quality & Delivery" }, items: [{ ko: "회귀 테스트 환경", en: "Regression harness" }, { ko: "CI 품질 게이트", en: "CI quality gates" }, "JUnit", "GitHub Actions", "Docker", "Google Cloud Run", "Prometheus"] },
  ],
  contact: { eyebrow: { ko: "LET'S TALK", en: "LET'S TALK" }, title: { ko: "안정적인 서비스를 함께 만듭니다", en: "Let's build reliable services together" }, copy: { ko: "프로젝트나 포지션 제안은 이메일로 연락해 주세요.", en: "For project or role opportunities, feel free to reach out by email." }, email: "jigwan.joe@gmail.com", github: "https://github.com/jgjoe" },
};
