export const pick = (value, lang) => value && typeof value === "object" && !Array.isArray(value) && ("ko" in value || "en" in value) ? value[lang] ?? value.ko : value;

export const portfolio = {
  name: { ko: "조지관", en: "Jigwan Joe" },
  role: { ko: "IT 시스템 및 소프트웨어 품질 엔지니어", en: "IT Systems & Software Quality Engineer" },
  ui: {
    about: { ko: "소개", en: "About" }, projects: { ko: "프로젝트", en: "Projects" }, credentials: { ko: "이력", en: "Credentials" }, contact: { ko: "연락", en: "Contact" },
    viewWork: { ko: "대표 프로젝트 보기", en: "View selected work" }, resume: { ko: "PDF로 저장", en: "Save as PDF" }, skipToContent: { ko: "본문으로 바로가기", en: "Skip to content" }, languageLabel: { ko: "영문으로 보기", en: "View in Korean" },
    themeToLight: { ko: "라이트 모드로 보기", en: "Use light mode" }, themeToDark: { ko: "다크 모드로 보기", en: "Use dark mode" },
    menuOpen: { ko: "메뉴 열기", en: "Open menu" }, menuClose: { ko: "메뉴 닫기", en: "Close menu" },
    mobileNavigation: { ko: "모바일 포트폴리오 메뉴", en: "Mobile portfolio navigation" },
    closeDialog: { ko: "닫기", en: "Close dialog" },
    projectDeepDive: { ko: "프로젝트 상세 보기", en: "View project details" },
    evidenceLinks: { ko: "검증 근거", en: "Evidence" },
    viewEvidence: { ko: "검증 근거 보기", en: "View evidence" },
    evidenceModalIntro: { ko: "대표 결과와 공개된 검증 자료를 한 곳에서 확인할 수 있습니다.", en: "Review the key outcomes and public validation sources in one place." },
  },
  hero: {
    eyebrow: ["BACKEND", "DATA SYSTEMS", "SOFTWARE QUALITY"],
    title: { ko: "만들고 검증해 배포합니다", en: "Build and verify before shipping" },
    summary: { ko: "백엔드와 데이터 시스템을 만들고 테스트와 운영 지표로 확인합니다.", en: "I build backend and data systems, then verify them with tests and operational signals." },
    photoAlt: { ko: "조지관 프로필 사진", en: "Portrait of Jigwan Joe" },
    quickFacts: [
      { value: "4.04 / 4.5", label: { ko: "학점", en: "GPA" } },
      { value: { ko: "경기대 컴퓨터공학부", en: "Computer Engineering" }, label: { ko: "2026.02 졸업", en: "Graduated 2026.02" } },
      { kind: "list", label: { ko: "자격증", en: "Certificates" }, items: ["정보처리기사", "SQLD", "ADsP", "CSTS"] },
      { kind: "list", label: { ko: "어학", en: "Language" }, items: ["OPIc IH", "TOEIC 765"] },
    ],
  },
  proof: { title: { ko: "핵심 성과", en: "Key outcomes" }, items: [
    { kicker: { ko: "프로세스 인텔리전스", en: "PROCESS INTELLIGENCE" }, value: { ko: "실제 데이터셋 2개 / 테스트 190개", en: "2 real datasets / 190 tests" }, label: { ko: "브라우저 온보딩·Web·Agent·MCP가 같은 deterministic Core 사실을 사용하도록 검증", en: "Verified browser onboarding, Web, Agent, and MCP against the same deterministic Core facts" } },
    { kicker: { ko: "데이터 엔지니어링", en: "DATA ENGINEERING" }, value: { ko: "Clean 78/78 · 241.35M행", en: "78/78 Clean · 241.35M rows" }, label: { ko: "서울 공공자전거 실제 원천을 revision-aware 파이프라인으로 처리하고 trusted/quarantine까지 reconciliation", en: "Processed real Seoul Public Bike sources through a revision-aware pipeline with trusted/quarantine reconciliation" } },
    { kicker: { ko: "품질", en: "QUALITY" }, value: { ko: "OCR 배포 보류 → 재출시", en: "OCR held → re-shipped" }, label: { ko: "잔여 오답을 근거로 보류하고 확인 흐름 개선 후 재출시", en: "Held the release over residual OCR errors, then re-shipped after improving the confirmation flow" } },
  ] },
  about: {
    eyebrow: { ko: "HOW I WORK", en: "HOW I WORK" }, title: { ko: "경계를 설계하고 근거로 검증합니다", en: "I design boundaries and verify with evidence" },
    copy: { ko: "백엔드와 데이터 시스템의 책임 경계를 분명히 두고, 테스트·실데이터·운영 기록으로 결과를 확인합니다.", en: "I keep backend and data-system responsibilities explicit, then verify outcomes with tests, real data, and operational records." },
    strengths: [
      { title: { ko: "책임과 사실의 경계를 분리합니다", en: "Separate responsibility from authority" }, copy: { ko: "Spring Boot와 Python 서비스, TraceVerity의 deterministic Core와 AI처럼 각 계층이 맡을 계산과 인터페이스를 구분합니다.", en: "I separate what each layer may compute and expose, from Spring Boot/Python services to TraceVerity's deterministic Core and AI surfaces." } },
      { title: { ko: "검증 가능한 상태로 끝냅니다", en: "Finish with verifiable evidence" }, copy: { ko: "회귀 테스트, 실데이터 reconciliation, canary·QA 기록처럼 결과를 다시 확인할 수 있는 근거를 함께 남깁니다.", en: "I leave reproducible evidence behind through regression tests, real-data reconciliation, canary records, and QA logs." } },
    ],
  },
  projects: {
    eyebrow: { ko: "SELECTED WORK", en: "SELECTED WORK" }, title: { ko: "판단과 결과가 보이는 프로젝트", en: "Projects built around decisions and results" },
    copy: { ko: "맡은 문제와 판단 과정에 집중하고 결과에는 검증 근거를 연결했습니다.", en: "Each project focuses on the problem I owned, the decision I made, and the evidence behind the result." },
    featured: [
      {
        title: "TraceVerity", titleLines: ["TraceVerity", { ko: "Process Intelligence Workbench", en: "Process Intelligence Workbench" }], type: [{ ko: "개인", en: "Personal" }, { ko: "Process Intelligence", en: "Process Intelligence" }], period: "2026.09",
        lead: { ko: "사용자가 브라우저에서 로컬 CSV/XES/XES.GZ 이벤트 로그를 가져와 매핑·검증한 뒤 같은 deterministic 대시보드에서 즉시 분석할 수 있는 로컬 우선 Process Intelligence 제품이며, 두 실제 업무 프로세스로 검증했습니다.", en: "A local-first Process Intelligence product where a user can import a local CSV, XES, or XES.GZ event log in the browser, map and validate it, and immediately analyze it in the same deterministic dashboard, verified across two real business processes." },
        tech: ["Python", "DuckDB", "FastAPI", "React", "Power BI", "MCP"],
        visibleDetailIndexes: [1, 2],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "이벤트 로그 지표를 UI·BI·LLM이 각자 계산하면 같은 프로세스를 서로 다르게 해석할 수 있습니다. 분석 기능보다 먼저 하나의 신뢰 가능한 process truth 경계가 필요했습니다.", en: "If UI, BI, and LLM layers calculate event-log metrics independently, the same process can acquire conflicting interpretations. I needed one trustworthy process-truth boundary before adding analytical surfaces." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "generic CSV/XES 계약과 브라우저 온보딩을 만들고 FastAPI/React·5개 read-only 도구·Direct Agent·MCP를 같은 Core read path에 연결했습니다.", en: "I built the generic CSV/XES contract and browser onboarding, then connected FastAPI/React, five read-only tools, Direct Agent, and MCP to the same Core read path." } },
          { label: { ko: "판단", en: "Decision" }, copy: { ko: "AI는 authoritative metric을 계산하지 않고 5개 read-only 도구의 fact만 사용합니다. Web·Agent·MCP가 같은 deterministic Core를 읽어 별도 process truth를 만들지 않습니다.", en: "AI uses facts from five read-only tools instead of calculating authoritative metrics. Web, Agent, and MCP read the same deterministic Core rather than creating separate process truths." } },
          { label: { ko: "검증", en: "Verification" }, copy: { ko: "두 실제 데이터셋에서 Python 190/190, Playwright 2/2, Direct Agent 12/12, MCP Agent 12/12, Direct/MCP 비교 22/22를 통과했고 mismatch·grounding violation·forbidden-action violation은 모두 0건이었습니다. 현재 브라우저 온보딩 human cohort는 NOT RUN 상태입니다.", en: "Across two real datasets, the canonical project passed Python 190/190, Playwright 2/2, Direct Agent 12/12, MCP Agent 12/12, and 22/22 Direct/MCP comparisons, with zero mismatches, grounding violations, or forbidden-action violations. The current browser-onboarding human cohort remains NOT RUN." } },
          { label: { ko: "경계", en: "Boundary" }, copy: { ko: "로컬 우선 단일 사용자 제품이며 generic CSV/XES 브라우저 온보딩은 지원하지만 Power BI 증명은 BPIC12 전용입니다. observed event gap은 실제 queue/waiting이 아니고 설정 threshold는 실제 업무 SLA가 아닌 분석 시나리오입니다.", en: "This is a local-first single-user product with generic CSV/XES browser onboarding, while the Power BI proof remains BPIC12-specific. Observed event gap is not true queue/waiting time, and configured thresholds are analytical scenarios rather than actual business SLAs." } },
        ],
        results: [{ value: "2", label: { ko: "실제 데이터셋", en: "real datasets" } }, { value: "190 / 190", label: { ko: "Python regression", en: "Python regression" } }, { value: "12 / 12 × 2", label: { ko: "Direct Agent / MCP", en: "Direct Agent / MCP" } }],
        architecture: {
          variant: "hub",
          title: { ko: "하나의 process truth", en: "One process-truth boundary" },
          sources: ["BPI Challenge 2012 XES", "Help Desk CSV", { ko: "로컬 CSV/XES import", en: "Local CSV/XES import" }],
          hub: { name: "Python / DuckDB deterministic Core", copy: { ko: "authoritative process facts", en: "authoritative process facts" } },
          spokes: [
            { name: "Browser import", copy: { ko: "dataset contract · mapping · validation", en: "dataset contract · mapping · validation" } },
            { name: "FastAPI / React", copy: { ko: "같은 Core read path", en: "same Core read path" } },
            { name: "Agent / MCP", copy: { ko: "5개 read-only 도구의 fact만 사용", en: "facts from five read-only tools only" } },
            { name: "BPIC12 Power BI", copy: { ko: "별도 역사적 분석 표면", en: "separate historical surface" } },
          ],
          note: { ko: "AI와 presentation layer는 authoritative process metric을 독립 계산하지 않음", en: "AI and presentation layers do not independently calculate authoritative process metrics." },
        },
        links: [{ href: "https://github.com/jgjoe/TraceVerity", label: { ko: "코드 보기", en: "View code" } }, { href: "https://github.com/jgjoe/TraceVerity/blob/main/evidence/public-verification-summary.json", label: { ko: "공개 검증 요약", en: "Public verification summary" } }, { href: "https://github.com/jgjoe/TraceVerity/blob/main/docs/ARCHITECTURE.md", label: { ko: "아키텍처", en: "Architecture" } }, { href: "https://github.com/jgjoe/TraceVerity/blob/main/docs/REPRODUCTION.md", label: { ko: "재현 가이드", en: "Reproduction guide" } }],
        media: { type: "image", src: "/traceverity-overview.png", host: "github.com/jgjoe/TraceVerity", alt: { ko: "Italian Help Desk 데이터셋 분석 화면 위에 로컬 CSV/XES 가져오기 컨트롤을 연 TraceVerity", en: "TraceVerity with local CSV/XES import controls open above the Italian Help Desk dataset analysis" }, caption: { ko: "브라우저 온보딩과 같은 deterministic 대시보드의 imported-dataset 분석을 함께 보여주는 로컬 제품 화면", en: "Local product view showing browser onboarding and imported-dataset analysis in the same deterministic dashboard" } },
      },
      {
        title: "서울 공공자전거 데이터 파이프라인", titleLines: [{ ko: "서울 공공자전거", en: "Seoul Public Bike" }, { ko: "데이터 파이프라인", en: "Data Pipeline" }], type: [{ ko: "개인", en: "Personal" }, { ko: "데이터 엔지니어링", en: "Data Engineering" }], period: "2026.09",
        lead: { ko: "서울 공공자전거 실제 원천의 revision을 추적하고, 품질 문제가 있는 행·논리 그룹을 격리하며, 변경된 월만 재처리할 수 있게 만든 재현 가능한 배치 데이터 파이프라인입니다.", en: "A reproducible batch data pipeline for Seoul Public Bike data that tracks source revisions, quarantines row/group quality issues, and rebuilds only affected months." },
        tech: ["Python", "DuckDB", "Parquet", "SQL", "Apache Airflow"],
        visibleDetailIndexes: [1, 2],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "연·월 단위 원천 파일이 수정될 수 있고 대여소 정보는 snapshot으로만 관측됩니다. 단순 ETL보다 어떤 입력으로 무엇을 만들었는지와 수정 시 어디까지 다시 계산할지를 증명하는 구조가 필요했습니다.", en: "Yearly/monthly source files can be revised, while station information is observed only through snapshots. The system needed provable lineage and bounded recomputation rather than a one-off ETL." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "source size·SHA-256·기간을 manifest에 고정하고 immutable Raw/Clean, row/group DQ·quarantine, trusted fact와 세 종류 mart를 구현했습니다.", en: "I pinned source size, SHA-256, and period in the manifest, then built immutable Raw/Clean layers, row/group DQ and quarantine, trusted facts, and three mart types." } },
          { label: { ko: "판단", en: "Decision" }, copy: { ko: "yearly ZIP revision은 실제로 바뀐 월만 rebuild합니다. Airflow는 transformation을 복제하지 않고 같은 Python business layer의 backfill·retry만 orchestration합니다.", en: "Yearly ZIP revisions rebuild only months whose contents changed. Airflow orchestrates backfill and retry over the same Python business layer instead of duplicating transformation logic." } },
          { label: { ko: "검증", en: "Verification" }, copy: { ko: "2020-01~2026-06 Clean 78/78을 처리해 source/Clean 241,350,472행 = trusted 241,320,806 + quarantine 29,666으로 reconciliation을 확인했습니다. 대표 2020-09 warehouse에서도 fact·station-day·OD·source-quality grain과 집계가 일치했고, 최종 release-candidate 회귀는 WSL 139 passed / 1 skipped와 Windows 3 passed를 통과했습니다.", en: "I processed all 78 Clean months from 2020-01 through 2026-06 and reconciled 241,350,472 source/Clean rows into 241,320,806 trusted plus 29,666 quarantined rows. A representative 2020-09 warehouse slice reconciled fact, station-day, OD, and source-quality grains; the final release-candidate regression passed 139 WSL tests with 1 skipped and 3 Windows state tests." } },
          { label: { ko: "경계", en: "Boundary" }, copy: { ko: "대여소 이력은 실제 변경일을 안다고 가정하지 않고 observed snapshot history로만 사용했습니다. downstream acceptance는 Fact/Quality/OD 9개월과 Station-day 1개월의 실제 materialization 근거이며, 78개월 전체 downstream이나 cloud production 운영으로 확대하지 않습니다.", en: "Station history is modeled only from observed snapshots rather than invented change dates. Downstream acceptance uses real materialization evidence for 9 Fact/Quality/OD months and 1 Station-day month; it is not presented as 78-month downstream materialization or cloud production operation." } },
        ],
        results: [{ value: "78 / 78", label: { ko: "production Clean 월", en: "production Clean months" } }, { value: "241.35M", label: { ko: "source / Clean 행", en: "source / Clean rows" } }, { value: "29,666", label: { ko: "quarantine 행", en: "quarantined rows" } }],
        architecture: {
          title: { ko: "revision-aware data reliability flow", en: "Revision-aware data reliability flow" },
          sources: [{ ko: "서울 공공자전거 대여이력", en: "Seoul bike rental history" }, { ko: "대여소 snapshot", en: "Station snapshots" }],
          stages: [
            { name: "Immutable Raw", copy: { ko: "manifest / SHA-256 / source version", en: "manifest / SHA-256 / source version" } },
            { name: "Clean + DQ", copy: { ko: "row/group quarantine + provenance", en: "row/group quarantine + provenance" } },
            { name: "Trusted Warehouse", copy: { ko: "fact + observed station history", en: "fact + observed station history" } },
            { name: "Marts + Airflow", copy: { ko: "changed-only backfill / retry", en: "changed-only backfill / retry" } },
          ],
          note: { ko: "검증된 immutable version만 atomic current pointer로 승격", en: "Only validated immutable versions are promoted through atomic current pointers." },
        },
        links: [{ href: "https://github.com/jgjoe/seoul-bike-data-pipeline", label: { ko: "코드 보기", en: "View code" } }, { href: "https://github.com/jgjoe/seoul-bike-data-pipeline/blob/main/docs/production-validation.md", label: { ko: "Production 검증", en: "Production validation" } }, { href: "https://github.com/jgjoe/seoul-bike-data-pipeline/blob/main/docs/prd-v1.0-final.md", label: { ko: "Frozen PRD", en: "Frozen PRD" } }],
        media: {
          type: "data-flow",
          label: { ko: "서울 공공자전거 데이터 신뢰성 흐름", en: "Seoul Public Bike data reliability flow" },
          sources: [{ ko: "대여이력 원천", en: "Rental history" }, { ko: "대여소 snapshot", en: "Station snapshots" }],
          steps: [
            { name: "Manifested Raw", copy: { ko: "SHA-256 · source version", en: "SHA-256 · source version" } },
            { name: "Clean + DQ", copy: { ko: "row/group quarantine", en: "row/group quarantine" } },
            { name: "Trusted Warehouse", copy: { ko: "fact · observed station history", en: "fact · observed station history" } },
            { name: "Marts", copy: { ko: "OD · station-day · source quality", en: "OD · station-day · source quality" } },
          ],
          callouts: [
            { value: "78 / 78", label: { ko: "Clean 월 처리", en: "Clean months processed" } },
            { value: { ko: "변경 월만", en: "Changed only" }, label: { ko: "revision backfill", en: "revision backfill" } },
            { value: "Airflow", label: { ko: "backfill / retry 제어", en: "backfill / retry control" } },
          ],
          caption: { ko: "원천 revision을 추적해 검증된 버전만 승격하고 영향받은 월만 다시 계산합니다.", en: "Tracks source revisions, promotes only validated versions, and recomputes only affected months." },
        },
      },
      {
        title: "혜택나침반", titleLines: [{ ko: "혜택나침반", en: "BenefitCompass" }], type: [{ ko: "개인", en: "Personal" }, { ko: "RAG 시스템", en: "RAG system" }], period: "2026.06 — 2026.09",
        lead: { ko: "공식 정책을 한 검색 경로로 통합한 RAG 서비스입니다. 검색된 정책만 근거로 답하도록 설계했습니다.", en: "A RAG service that unifies official policies into one search path and answers only from retrieved policy evidence." },
        tech: ["Spring Boot", "FastAPI", "pgvector", "React", "E5", "Prometheus"],
        visibleDetailIndexes: [1, 2],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "수천 개 정책이 흩어져 있고, 키워드 검색만으로는 자신에게 맞는 제도를 찾기 어려웠습니다.", en: "Thousands of policies were fragmented, and keyword search made relevant programs hard to discover." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "두 공식 출처의 13,589개 정책을 하나의 검색 경로로 통합했습니다. 17,609개 청크에서 임베딩 누락 0건을 확인했습니다.", en: "I unified 13,589 policies from two official sources into one search path and verified zero missing embeddings across 17,609 chunks." } },
          { label: { ko: "판단", en: "Decision" }, copy: { ko: "지역 데이터는 신뢰도가 부족해 제외했습니다. 리랭커는 필수 지표가 나빠져 배포하지 않았습니다.", en: "I excluded unreliable regional data and kept the reranker out when required metrics regressed." } },
          { label: { ko: "배포와 운영", en: "Delivery & operations" }, copy: { ko: "무트래픽 검증 뒤 API를 10% canary에서 100%로 승격하고 rollback 경로를 보존했습니다. 요청 ID와 메트릭으로 API / ML / DB 구간을 나눠 관측했습니다.", en: "I promoted the API from a 10% canary to 100% after no-traffic validation, preserved rollback, and separated API, ML, and DB observability." } },
          { label: { ko: "한계", en: "Limit" }, copy: { ko: "첫 요청 지연은 scale-to-zero 비용 절충으로 남아 있습니다. 더 강한 사용자 의도 평가도 설계했지만 유효한 canonical 평가까지 완료되지 않아 성능 개선으로 주장하지 않았습니다.", en: "Cold first-request latency remains a scale-to-zero cost trade-off. I also designed a stronger user-intent evaluation, but it did not reach a valid canonical result, so I did not turn it into a performance claim." } },
        ],
        results: [{ value: "13,589", label: { ko: "공식 정책", en: "official policies" } }, { value: "17,609", label: { ko: "검색 청크", en: "search chunks" } }, { value: "0", label: { ko: "임베딩 누락", en: "missing embeddings" } }],
        architecture: {
          variant: "decision",
          title: { ko: "검색 품질을 배포 판단으로 연결", en: "Turn retrieval quality into a release decision" },
          sources: [{ ko: "온통청년", en: "Youth policies" }, { ko: "정부24", en: "Gov24" }],
          stages: [
            { name: "Normalize + chunk", copy: { ko: "13,589개 정책 · 17,609개 청크", en: "13,589 policies · 17,609 chunks" } },
            { name: "Hybrid retrieval", copy: { ko: "production-parity 평가", en: "production-parity evaluation" } },
            { name: "Grounded answer", copy: { ko: "검색된 정책만 근거로 응답", en: "answers from retrieved policies only" } },
          ],
          decision: {
            label: { ko: "Reranker 후보", en: "Reranker candidate" },
            result: { ko: "필수 지표 악화 → NO-GO", en: "Required metrics regressed → NO-GO" },
            action: { ko: "공개 경로 RERANK=0 유지", en: "Public path kept at RERANK=0" },
          },
          note: { ko: "좋아 보이는 변경보다 동일 조건의 측정 결과를 배포 기준으로 사용", en: "Release decisions follow like-for-like measurements rather than a promising-looking change." },
        },
        links: [{ href: "https://jgjoe.github.io/benefit-compass", label: { ko: "데모 보기", en: "View demo" } }, { href: "https://github.com/jgjoe/benefit-compass", label: { ko: "코드 보기", en: "View code" } }, { href: "https://github.com/jgjoe/benefit-compass/tree/main/eval", label: { ko: "평가셋과 측정 스크립트", en: "Evaluation set & scripts" } }, { href: "https://github.com/jgjoe/benefit-compass/blob/main/docs/operations/PRODUCTION_LAB_2_2026-07-21.md", label: { ko: "운영 실험 기록", en: "Production lab record" } }, { href: "https://github.com/jgjoe/benefit-compass/blob/main/docs/operations/RUNBOOK.md", label: { ko: "운영 런북", en: "Runbook" } }],
        media: { type: "image", src: "/benefit-compass-demo.png", host: "jgjoe.github.io/benefit-compass", alt: { ko: "혜택나침반의 월세 지원 검색 결과", en: "BenefitCompass search results for rental support" }, caption: { ko: "실제 배포 환경에서 확인한 검색 결과", en: "Search result captured from the live deployment" } },
      },
      {
        title: "오늘도 신선", titleLines: [{ ko: "오늘도 신선", en: "Fridge D-Day" }], type: [{ ko: "개인", en: "Solo" }, { ko: "Android 공개 출시", en: "Android release" }, "Closed Alpha"], period: { ko: "2025.09 — 진행 중", en: "2025.09 — Present" },
        lead: { ko: "OCR로 유통기한 입력을 줄이고 이미지는 기기 안에서 처리하는 Android 앱입니다. ONEstore v2.0.0과 Google Play Closed Alpha까지 출시했습니다.", en: "An Android expiry-date app with on-device OCR, publicly shipped as ONEstore v2.0.0 and Google Play Closed Alpha." },
        tech: ["Kotlin", "Jetpack Compose", "Room", "WorkManager", "ML Kit OCR", "MVVM"],
        visibleDetailIndexes: [1, 2],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "기존 앱은 수동 입력이 번거롭고 인터넷 연결과 개인정보 수집에 대한 부담이 있었습니다.", en: "Existing apps relied on tedious manual input and raised concerns around connectivity and personal data." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "OCR 기반 입력과 로컬 저장을 구현했습니다. 알림부터 위젯과 백업/복원까지 단독으로 완성했습니다.", en: "I built OCR input and local storage, then completed notifications, widgets, and backup/restore solo." } },
          { label: { ko: "판단", en: "Decision" }, copy: { ko: "이미지는 기기 안에서만 처리했습니다. 잔여 OCR 오답이 있는 후보는 자동 게이트를 통과해도 배포하지 않았습니다.", en: "Images stay on-device, and I did not ship candidates with residual OCR errors even after automated gates passed." } },
          { label: { ko: "품질 검증", en: "Quality gate" }, copy: { ko: "독립 한국 라벨 55장을 고정 회귀셋으로 반복 검증하고, 잔여 오인식과 표본 공백이 남은 후보는 자동 게이트를 통과해도 배포를 보류했습니다. 최종 v2.0.0/code5 exact RC는 JVM unit 107/107, lint 0 errors, Galaxy A32 non-OCR instrumentation 65/65를 통과했습니다.", en: "I repeatedly tested OCR changes against a fixed set of 55 independent Korean labels and held a candidate despite passing automated gates when residual misreads and coverage gaps remained. The final v2.0.0/code5 exact RC passed 107/107 JVM unit tests, lint with zero errors, and 65/65 non-OCR instrumentation tests on a Galaxy A32." } },
          { label: { ko: "그 다음", en: "What followed" }, copy: { ko: "인식 날짜를 사용자가 확인해야 저장되도록 바꿔 v1.0.2로 재출시한 뒤, bundled Korean OCR과 실기기 회귀를 검증했습니다. 이어 4명 usability에서 반복 마찰을 찾아 수정하고 affected user 재검증을 거쳐 v2.0.0/code5를 ONEstore에 공개 배포하고 Google Play closed Alpha에도 출시했습니다. Play의 14일 요건과 Production 공개는 아직 진행 중입니다.", en: "I required users to confirm recognized dates before saving and re-released v1.0.2, then verified bundled Korean OCR and same-device regression. After a four-person usability round exposed repeated friction, I fixed those flows, retested them with affected users, publicly shipped v2.0.0/code5 on ONEstore, and released it to Google Play closed Alpha. Play's 14-day requirement and Production release are still in progress." } },
        ],
        results: [{ value: { ko: "검증 통과", en: "All checks passed" }, label: { ko: "JVM 107/107\nA32 65/65", en: "JVM 107/107\nA32 65/65" } }, { value: { ko: "Closed Alpha", en: "Closed Alpha" }, label: { ko: "Google Play v2.0.0/code5", en: "Google Play v2.0.0/code5" } }, { value: { ko: "공개 3버전", en: "3 public versions" }, label: { ko: "ONEstore v1.0 → v1.0.2 → v2.0.0", en: "ONEstore v1.0 → v1.0.2 → v2.0.0" } }],
        links: [{ href: "https://m.onestore.co.kr/v2/ko-kr/app/0001003331", label: { ko: "스토어에서 보기", en: "View in store" } }, { href: "https://github.com/jgjoe/Fridge-D-Day", label: { ko: "코드 보기", en: "View code" } }, { href: "https://github.com/jgjoe/Fridge-D-Day/blob/main/QA_RELEASE_RECORD.md", label: { ko: "QA와 릴리스 기록", en: "QA & release record" } }, { href: "https://github.com/jgjoe/Fridge-D-Day/blob/main/docs/qa/OCR_BENCHMARK.md", label: { ko: "OCR 벤치마크", en: "OCR benchmark" } }, { href: "https://github.com/jgjoe/Fridge-D-Day/blob/main/.github/workflows/android-ci.yml", label: { ko: "CI 설정", en: "CI workflow" } }],
        media: { type: "gallery", label: { ko: "오늘도 신선 v2 대표 화면", en: "Fridge D-Day v2 highlights" }, images: [
          { src: "/today-fresh-1.png", alt: { ko: "오늘도 신선 v2 Today 화면", en: "Fridge D-Day v2 Today screen" } },
          { src: "/today-fresh-2.png", alt: { ko: "오늘도 신선 v2 Scan 화면", en: "Fridge D-Day v2 Scan screen" } },
          { src: "/today-fresh-3.png", alt: { ko: "오늘도 신선 v2 Record 화면", en: "Fridge D-Day v2 Record screen" } },
        ] },
      },
      {
        title: "길동이 AI 차량 어시스턴트", titleLines: [{ ko: "길동이", en: "GildongE" }, { ko: "AI 차량 어시스턴트", en: "AI Vehicle Assistant" }], type: [{ ko: "6인 팀", en: "Team of 6" }, { ko: "백엔드 / DB 담당", en: "Backend / DB owner" }], period: "2025.03 — 2025.06",
        lead: { ko: "여러 장치의 차량 데이터를 처리하는 Spring Boot 백엔드를 맡았습니다.", en: "I owned the Spring Boot backend that processed vehicle data from multiple devices." },
        tech: ["Java 17", "Spring Boot", "MongoDB", "Spring Data MongoDB", "Kakao OAuth API", "OpenAPI"],
        visibleDetailIndexes: [0, 1],
        details: [
          { label: { ko: "문제", en: "Problem" }, copy: { ko: "장치별 형식이 다른 차량 데이터를 사용자 단위로 다룰 서버가 필요했습니다.", en: "The team needed a backend that could normalize device-specific vehicle data per user." } },
          { label: { ko: "기여", en: "Ownership" }, copy: { ko: "차량 도메인 REST API와 MongoDB 모델을 설계했습니다. 카카오 사용자 흐름과 주간 평균 집계도 구현했습니다.", en: "I designed the vehicle-domain REST APIs and MongoDB models, plus Kakao user flows and weekly aggregates." } },
          { label: { ko: "담당 범위", en: "My scope" }, copy: { ko: "6인 팀에서 차량 도메인 백엔드와 MongoDB 데이터 모델을 담당했습니다.", en: "In a six-person team, I owned the vehicle-domain backend and MongoDB data model." } },
        ],
        results: [{ value: { ko: "은상", en: "Silver" }, label: { ko: "캡스톤디자인 경진대회", en: "Capstone Design award" } }, { value: { ko: "1편", en: "1" }, label: { ko: "학회 논문", en: "Conference paper" } }, { value: { ko: "5개", en: "5" }, label: { ko: "백엔드 도메인", en: "backend domains" } }],
        links: [{ href: "https://github.com/jgjoe/gildongE", label: { ko: "백엔드 코드 보기", en: "View backend code" } }],
        media: { type: "poster", src: "/gildongE_poster.jpg", alt: { ko: "길동이 프로젝트 포스터", en: "GildongE project poster" } },
      },
    ],
    posterOpen: { ko: "프로젝트 포스터 보기", en: "View project poster" },
    posterClose: { ko: "프로젝트 포스터 닫기", en: "Hide project poster" },
    moreEyebrow: { ko: "MORE WORK", en: "MORE WORK" }, moreTitle: { ko: "다른 환경에서도 문제를 풀어봤습니다", en: "More problems, different environments" },
    more: [
      { title: { ko: "쓰담", en: "SSeudam" }, type: ["YOLOv8", "Android", "Robot"], link: null, copy: { ko: "실시간 객체 탐지와 로봇 연동을 맡아 2024 한국정보기술학회 대학생 논문경진대회 우수논문상을 받았습니다.", en: "I handled real-time object detection and robot integration in a project that received a 2024 KIIT student paper award." }, media: { src: "/ssodam_poster.jpg", alt: { ko: "쓰담 프로젝트 포스터", en: "SSeudam project poster" } } },
      { title: "movie_diary", type: ["React", "FastAPI", "Cloud Run"], link: "https://github.com/jgjoe/movie_diary", copy: { ko: "감정 기반 영화 추천 서비스로 외부 API 연동과 Cloud Run 배포 자동화를 구현했습니다.", en: "I built an emotion-based film recommendation service with third-party APIs and Cloud Run deployment automation." } },
      { title: "Build-Your-Health", type: ["JSP/Servlet", "MySQL"], link: "https://github.com/jgjoe/Build-Your-Health", copy: { ko: "건강 기록부터 쇼핑과 게시판, 관리자 기능까지 단독 구현한 MVC 웹 애플리케이션입니다.", en: "Solo MVC web app spanning health logs, commerce, community, and admin CRUD." } },
      { title: { ko: "Kubernetes 운영 실습", en: "Kubernetes Operations Lab" }, type: ["Kubernetes", "kind", "Docker"], link: "https://github.com/jgjoe/kubernetes-ops-lab", copy: { ko: "kind 환경에서 Pod self-healing, readiness/liveness, 실패한 rollout 진단·rollback을 직접 재현해 Kubernetes의 상태 변화와 복구 과정을 검증한 운영 실습입니다.", en: "A local kind lab reproducing pod self-healing, readiness/liveness behavior, and failed-rollout diagnosis and rollback to verify Kubernetes state transitions and recovery." } },
    ],
  },
  credentials: {
    eyebrow: { ko: "CREDENTIALS", en: "CREDENTIALS" }, title: { ko: "기본기를 증명하는 이력", en: "Credentials that support the work" }, skillsTitle: { ko: "핵심 기술", en: "CORE STACK" },
    groups: [
      { title: { ko: "학력", en: "Education" }, items: [{ ko: "경기대학교 컴퓨터공학부 졸업", en: "B.S. in Computer Engineering, Kyonggi University" }, { ko: "2020.03 — 2026.02 / 학점 4.04/4.5", en: "Mar. 2020 — Feb. 2026 / GPA 4.04/4.5" }] },
      { title: { ko: "자격증", en: "Certificates" }, items: ["정보처리기사", "SQLD", "ADsP", "CSTS Foundation Level"] },
      { title: { ko: "연구와 수상", en: "Research & awards" }, items: [{ ko: "한국정보기술학회 논문 2편 공저", en: "Co-author of 2 KIIT conference papers" }, { ko: "2025 산학협력 캡스톤디자인 경진대회 심화캡스톤디자인 부문 은상", en: "2025 Industry-Academia Capstone Design Competition, Advanced Division Silver Prize" }, { ko: "2024 한국정보기술학회 대학생 논문경진대회 우수논문상", en: "2024 KIIT Student Paper Competition, Outstanding Paper Award" }] },
    ],
  },
  skills: [
    { title: { ko: "언어와 백엔드", en: "Languages & Backend" }, items: ["Java", "Kotlin", "Python", "SQL", "Spring Boot", "FastAPI", "REST API", "OpenAPI"] },
    { title: { ko: "데이터 시스템", en: "Data & Systems" }, items: ["DuckDB", "Parquet", "PostgreSQL / pgvector", "MongoDB", "MySQL", "Apache Airflow"] },
    { title: { ko: "품질과 배포", en: "Quality & Delivery" }, items: ["Pytest", "Playwright", "JUnit", "GitHub Actions", "Docker", "Prometheus", "Google Cloud Run"] },
  ],
  contact: { eyebrow: { ko: "LET'S TALK", en: "LET'S TALK" }, title: { ko: "안정적인 서비스를 함께 만듭니다", en: "Let's build reliable services together" }, copy: { ko: "프로젝트나 포지션 제안은 이메일로 연락해 주세요.", en: "For project or role opportunities, feel free to reach out by email." }, email: "jigwan.joe@gmail.com", github: "https://github.com/jgjoe" },
};
